name: Build Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    uses: Yueby/shared-workflows/.github/workflows/unity-package-release.yml@main
    with:
      package-name: ${{ vars.PACKAGE_NAME }}