name: Build Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: Yueby/shared-workflows/.github/workflows/unity-package-release.yml@main
    with:
      package-name: ${{ vars.PACKAGE_NAME }}
      configuration: ".github/changelog-config.json"