name: Build Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
      actions: write
    uses: Yueby/shared-workflows/.github/workflows/unity-package-release.yml@main
    with:
      package-name: ${{ vars.PACKAGE_NAME }}

  trigger-other:
    needs: release
    if: ${{ vars.TARGET_REPO != '' }}
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ vars.TARGET_REPO }}/actions/workflows/${{ vars.TARGET_WORKFLOW }}/dispatches \
            -d '{"ref":"main","inputs":{}}'